version: "3"
services:
  front:
    container_name: front
    image: "node:14"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    working_dir: /home/node/app
    volumes:
      - ./front:/home/node/app
    ports:
      - "3000:3000"
    command: "yarn start"
    networks:
      - frontend

  back:
    container_name: back
    image: "node:14"
    environment:
      - SERVER_PORT=4000
    working_dir: /home/node/app
    volumes:
      - ./back:/home/node/app
    ports:
      - "4000:4000"
    command: "yarn dev"
    networks:
      - frontend

networks:
  frontend: